server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.46.151.189:8000/user
    username: root
    password: Heyjude259?


  session:
    store-type: none #mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

thymeleaf:
  prefix: classpath:/templates/  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  content-type: text/html
  mode: LEGACYHTML5

#redis
#redis:
#  host:8081 #默认为localhost
#  password: 123424 #默认为空
#  timeout: PT30M #30分钟
##spring-session


